"""empty message

Revision ID: 930c115fbbcd
Revises: 
Create Date: 2024-06-18 02:28:23.768492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930c115fbbcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('guest_name', sa.String(length=15), nullable=False),
    sa.Column('plusone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guest_name', name=op.f('pk_guests'))
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=15), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('guest', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['guest'], ['guests.guest_name'], name=op.f('fk_food_guest_guests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food')),
    sa.UniqueConstraint('item_name', name=op.f('uq_food_item_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    op.drop_table('guests')
    # ### end Alembic commands ###
